# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: In-ear Gems
subtitle: "Hi-fi in the pocket"
email: gen.tran.1991@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  In-ear Gems
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iegems.nk-tran.com/" # the base hostname & protocol for your site, e.g. http://example.com
# url: "" # This one is for local testing
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# minimal_mistakes_skin: "contrast"

logo: "/assets/images/in-ear-gems-2.png"

search: true

author:
  name: "NKT"
  avatar: "/assets/images/In-ear-gems-2.png"
  bio: "I am geeky about IEMs"
  location: "Down the rabbit hole"
  links:
  - label: "Homepage"
    icon: "fas fa-fw fa-link"
    url: "https://nk-tran.com"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/nktrandlt"

paginate: 5 # amount of posts to show
paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      comments: true
      layout: single
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true